- README.md
- pipelines/build-release.yml
- pipelines/destroy.yml
- pipelines/setup.yml
- scripts/build-boshrelease-pipelines.sh
- scripts/deploy-setup-pipelines.sh
- scripts/fly_sync_and_login.sh
- terraform/buckets-boshreleases.tf
- terraform/variables.tf
[#131375099 Check health of cell components](https://www.pivotaltracker.com/story/show/131375099)
What?
-----
I want to extend this project to include a new bosh-release, but I don't want to have to deploy a complete concourse and bosh release to test the changes. Instead, I want to be able to use my concourse from paas-cf.
This PR adds the capacity to override the concourse url and buckets to allow so.
How to test?
------------
Code sanity check.
you can try against your own concourse in paas-cf by doing:
```
export DEPLOY_ENV=....
export CONCOURSE_ATC_PASSWORD=.....
STATE_BUCKET=${DEPLOY_ENV}-state \
RELEASES_BUCKET_NAME=${DEPLY_ENV}-releases-state \
BRANCH=$(git rev-parse --abbrev-ref HEAD) \
CONCOURSE_URL=https://deployer.${DEPLOY_ENV}.dev.cloudpipeline.digital \
make dev pipelines …
```
> [#131375099] Allow customise the settings for the target concourse

- scripts/build-boshrelease-pipelines.sh
[#131375099 Check health of cell components](https://www.pivotaltracker.com/story/show/131375099)
What?
-----
We are extending https://github.com/alphagov/paas-datadog-for-cloudfoundry-boshrelease/ to monitor the cell components, and we want to add it to these build server.
In this PR we also refactor the script to make it easier to add new releases.
Dependencies
------------
~~This PR is build over the PR https://github.com/alphagov/paas-release-ci/pull/2 which should be merged first. That PR allows test with the paas-cf concourse.~~  (merged)
How to review?
--------------
Code check.
Then you can test creating a build server:
```
export DEPLOY_ENV=....
BRANCH=$(git rev-parse --abbrev-ref HEAD) \
make dev pipelines
```
or using the paas-cf from concourse:
```
export DEPLOY_ENV=.... …
```
> [#131375099] Add datadog-for-cloudfoundry to the list of bosh-releases to build

- scripts/build-boshrelease-pipelines.sh
I add this in the scope of https://www.pivotaltracker.com/story/show/132745311 but the story is not being played now. It is only for cross reference.
What?
----
I add this project to the concourse ci as I am working on https://github.com/alphagov/paas-haproxy-release/pull/7
The release is ours (no fork) and it is called paas-haproxy.
How to review?
-----------
check it makes sense
who?
---
Anyone but @keymon
> [#132745311] Add our release paas-haproxy-release

- pipelines/build-release.yml
[#135320595 - Rework Pull requests resource PR](https://www.pivotaltracker.com/story/show/135320595)
The upstream author has accepted the new functionality to prevent
pull requests from forked repositories from generating new versions
of the resource. This will stop untrusted code being pulled into our
pipeline and potentially executing arbitrary code.
The version with this functionality is tagged as v20[1]
[1] https://github.com/jtarchie/pullrequest-resource/tree/v20
Assert that pull requests from forks do not trigger the build of Bosh releases in our build pipeline.
* Deploy a build environment using paas-bootstrap. If you haven't done that before we can have a chat about how it is done. The key part is not setting `DEPLOY_ENV` to the same as your CF deployment.
* Configure its …
> [#135320595] Use upstream pull request resource

- scripts/build-boshrelease-pipelines.sh
We have decided to fork sap ipsec release so that we store the final build in our bucket, just in case they decide to pull it. This PR is to automate that build.
See [pivotal story](https://www.pivotaltracker.com/n/projects/1275640/stories/136558969) for more context.
Make sure build succeeds. You can use `ipsec_release_131802383` branch in paas-cf to deploy and test that this works: fork the branch and modify the last tmp commit to use the newly built final release. Deploy CF, watch acceptance tests pass. Or you can follow instructions from https://github.com/alphagov/paas-cf/pull/684
not @mtekel or @paroxp
> [#136558969] Add ipsec release

- pipelines/build-release.yml
I think the `130188061_add_bash_to_boshcli` tag was merged here unintentionally and was a leftover from testing.
Make sure that it looks sane.
Not me
> [CLEANUP] Leftover removal

- .travis.yml
- Makefile
- README.md
- app-deploy.d/tech-docs
- pipelines/deploy-app.yml
- pipelines/setup.yml
- scripts/build-app-deployment-pipelines.sh
- scripts/deploy-setup-pipelines.sh
- scripts/environment.sh
- scripts/scripts_suite_test.go
- scripts/upload-cf-cli-secrets.sh
- scripts/val_from_yaml.rb
- scripts/val_from_yaml_test.go
Story: [Deployment Pipeline for Tech Docs to cloudapps.digital](https://www.pivotaltracker.com/story/show/136353551)
Automate the deployment of the paas-tech-docs application. It was made in a generic way so any application can be deployed in a similar fashion.
Depends on PR https://github.com/alphagov/paas-tech-docs/pull/12
* Deploy your own dev release Concourse using the README on this branch (you could use your deployer but you may not be able to test the setup pipeline)
* Upload CF API credentials:
```    
DEPLOY_ENV=XXX CF_USER=admin CF_PASS=XXX make dev upload-cf-cli-secrets
```
* Push the setup pipeline (follow the README for details):
```
DEPLOY_ENV=XXX CF_ORG=admin CF_SPACE=admin BRANCH=deploy-tech-docs-136353551 make dev pipelines
```
* The tech-docs app should deploy to your …
> [#136353551] Deploy tech docs application

- pipelines/deploy-app.yml
- scripts/build-boshrelease-pipelines.sh
- scripts/deploy-setup-pipelines.sh
- scripts/environment.sh
Story: [Deployment Pipeline for Tech Docs to cloudapps.digital](https://www.pivotaltracker.com/story/show/136353551)
1. https://github.com/alphagov/paas-release-ci/pull/13 broke in CI because $CF_API_SECURE didn't have a default value.
1. As we forced using $CF_API, $CF_USER and $CF_PASSWORD, we caused a problem for developers caring only about bosh releases. Setting default values solved it too.
1. Run `make dev pipelines` without setting $CF_API
1. Simulate CI by removing `$(eval export CF_API_SECURE=--skip-ssl-validation)` from the Makefile and running `make dev pipelines`
Not me
> [#136353551] Deploy tech docs - Fixes

- app-deploy.d/paas-tech-docs
Story: [Deployment Pipeline for Tech Docs to cloudapps.digital](https://www.pivotaltracker.com/story/show/136353551)
To match the official name of the app deployed in production.
Code review
* Delete tech-docs CI pipeline
* Delete tech-docs app in prod
Not me
> [#136353551] Rename tech-docs app to paas-tech-docs

- app-deploy.d/paas-product-page
As the tech-docs have proven to work with its approach, we'd like to use it for our product-page as well.
We're simply adding another app configuration, that will be considered in the loop.
* Deploy your own dev release Concourse using the README on this branch (you could use your deployer but you may not be able to test the setup pipeline)
* Upload CF API credentials:
```    
DEPLOY_ENV=XXX CF_USER=admin CF_PASS=XXX make dev upload-cf-cli-secrets
```
* Push the setup pipeline (follow the README for details):
```
DEPLOY_ENV=XXX BRANCH= automated_deployment_140832481 make dev pipelines
```
* The `product-page` app should deploy to your environment automatically
Not @paroxp
> [#140832481] Add product page to app deployment

- scripts/build-boshrelease-pipelines.sh
This has changed now that we have a separate repository for the Bosh
release, which submodules in the CDN broker.
This was done because it allows us to contribute changes upstream and
it stops us breaking Go import paths. We still need to fix the three-
pull-request dance we do when developing Bosh releases, but that can
be addressed as a different piece of work (preferably on the RDS broker,
since it is more stable and is not a fork).
Check the path matches the path to the repository in GitHub
Anyone but @combor or me.
> [#141231851] Fix path to CDN broker Bosh release repository

- pipelines/build-release.yml
- pipelines/deploy-app.yml
- pipelines/destroy.yml
- pipelines/setup.yml
So that we can control how containers are updated between environments and
prevent forwards/backwards incompatibilities with code in the pipeline.
This will also prevent Concourse from re-downloading all of the containers
each time we merge a change to alphagov/paas-docker-cloudfoundry-tools
because Docker Hub rebuilds everything.
Using the functionality added in:
- alphagov/paas-docker-cloudfoundry-tools#93
1. Eyeball the diff and make sure that it looks sensible
1. Run at least one pipeline and confirm that it still works
Not @dcarley
> [#145211537] Pin all governmentpaas containers to a version

- scripts/fly_sync_and_login.sh
Now that we have signed certs for the concourse it's no longer necessary
to skip SSL validation when accessing it.
Run `make dev pipelines` from this branch and verify that it works. Run the setup pipeline and verify that the self-update step works.
Not me.
> [#141423205] Don't skip SSL validation for concourse.

- Makefile
- README.md
- pipelines/setup.yml
- scripts/deploy-pipeline.sh
- scripts/deploy-setup-pipelines.sh
It has long confused me that you need to manually run the `setup` pipeline
when you create a Build Concourse in a dev environment, but then *all* of
the other pipelines run and start submitting build results back to GitHub.
I think it makes more sense to automatically trigger the `setup` pipeline
but pause all of the release pipelines. Then you can unpause the release
that you intend to work on.
I've set the `setup` and `destroy` pipelines to explicitly not be paused.
I have tested this and I think code review only would be acceptable.
If you'd prefer to test it yourself, the instructions are:
1. Have a Concourse to deploy to:
- Ideally create a "build" Concourse using [paas-bootstrap](https://github.com/alphagov/paas-bootstrap) with a different `DEPLOY_ENV` from your "deployer".
- You …
> [#140847887] Change pipeline pausing in dev

- scripts/build-boshrelease-pipelines.sh
We want to introduce new pipelines to test pull requests on the code repos,
e.g. paas-rds-broker rather than paas-rds-broker-boshrelease. The existing
naming makes this confusing.
We need to use a command with a FIXME comment to rename the pipelines
in-place so that the build history is kept. This should be a noop on the 2nd
run. Then the `rename-pipeline` command can be removed.
1. Deploy a "build" Concourse using [paas-bootstrap](https://github.com/alphagov/paas-bootstrap) making sure that you use a different `DEPLOY_ENV` from your "deployer" Concourse.
1. Upload pipelines from the `master` branch:
git checkout master
git pull
make dev pipelines
1. Run the `setup` pipeline and confirm that it creates all of the BOSH release pipelines.
1. Upload pipelines from this branch:
git fetch
git …
> [#140847887] Rename release pipelines to have -release suffix

- pipelines/setup.yml
The self-update-pipelines currently will error if the concourse password
is changed. This is because the password is passed around in a loop, and
therefore the new one isn't pulled from the S3 bucket. Breaking this
loop means that the password will be pulled from S3 each time, and
therefore will be updated.
* Deploy the pipelines from this branch to a build concourse.
* Rotate the credentials for the build concourse
* Verify that the setup pipeline runs correctly with the new credentials.
Note: Due to the fact that the creds for CI have already been rotated, the pipelines will still need to be manually pushed there to fix it. This should prevent this breaking again in future though.
Not me.
> [#146152015] Handle concourse password changes in self-update-pipelines

- pipelines/deploy-app.yml
Because I don't know what Cloud Foundry will do if two commits land on the
master branch in quick succession and result in two parallel deployments
happening at the same time.
I noticed this because app deployments are currently broken by credential
rotation in Pivotal story #146152015 and this has caused several builds to
get stuck in the pending state.
It is still safe to run the test task in parallel.
I checked that this is syntactically correct and applies to a build Concourse. I haven't tested that it does that I've told it when multiple builds are run, because I don't have a CF environment up at the moment. Given that small change and that it's a Concourse feature I think code review only is sufficient.
Anyone
> [#146152015] Deploys apps in serial

- Makefile
- pipelines/integration-test.yml
- pipelines/setup.yml
- scripts/integration-test-pipelines.sh
- scripts/pipecleaner.py
Introduces a pattern for running integration tests for pull requests on code
repos (which are later consumed by BOSH release repos).
Each one should have a `ci/integration.yml` file defining the task to run
the tests and assumes a single input directory called `pr`. Build status
will be submitted back to GitHub.
At the moment we only have paas-rds-broker.
1. Review the code and commits.
1. Create a Build Concourse using [paas-bootstrap](https://github.com/alphagov/paas-bootstrap) (use a different `DEPLOY_ENV` from your Deployer Concourse!).
1. Checkout this branch and deploy pipelines:
git fetch && git checkout feature/140847887-integration_test_pipelines
BRANCH=$(git rev-parse --abbrev-ref HEAD) make dev pipelines
1. Wait for the `setup` pipeline to auto-trigger and create the other …
> [#140847887] Run integration tests for paas-rds-broker

- .travis.yml
- Makefile
- pipelines/integration-test.yml
- pipelines/setup.yml
- scripts/integration-test-pipelines.sh
- scripts/pipecleaner.py
- scripts/upload-compose-secrets.sh
This PR adds an integration configuration and version file for running integration tests on PRs via Concourse in the CI environment. In addition pipecleaner has had to have some additional work undertaken in order to handle external task files and resources loaded in the main pipeline and then consumed in the external task file.
1. https://github.com/alphagov/paas-credentials/pull/82 needs to be merged first
1. Create a dev build concourse via paas-bootstrap
1. Upload compose secrets with `make dev upload-compose-secrets`
1. Push the pipelines from this branch `make dev pipelines` for setup, `make dev integration-test-pipelines` for the integration pipelines, these include the new test and tag pipeline.
1. Run the Setup pipeline, this will generate a SSH keypair
1. Login to Github with …
> [#147445891] Compose integration tests

- pipelines/build-release.yml
- pipelines/destroy.yml
- pipelines/integration-test.yml
- pipelines/setup.yml
- scripts/deploy-pipeline.sh
- scripts/deploy-setup-pipelines.sh
- scripts/fly_sync_and_login.sh
We'd like to catchup with the releases of deployer and bootstrap Concourse, and estimated upgrading to the latest one will satisfy us best.
- We're far behind
- We're not upgrading as often as we'd wish to
- It contains a lot of fixes reported over time, including a change to container volumes that we think should prevent the need to "shake" Concourse
These instructions rely on self-updating pipelines. Please ensure that you are not disabling them in your dev environment.
:bee: :bee: :bee:
1. There is a `WIP` commit which must not be merged as is. It will need to be updated after the alphagov/paas-semver-resource#7 and alphagov/paas-s3-resource#6 are merged.
:bee: :bee: :bee:
You may wish to use a different `DEPLOY_ENV` for this so that you don't affect your existing dev environment.
- …
> [#150512756] Upgrade concourse

- .github/PULL_REQUEST_TEMPLATE.md
Github now supports templates for PRs[1]. This adds a template that
follows the recommendations in the team manual[2]
[1]https://github.com/blog/2111-issue-and-pull-request-templates
[2]https://government-paas-team-manual.readthedocs.org/en/latest/team/working_practices/#pull-requests
> Add a pull-request template

- pipelines/deploy-app.yml
The existing code did not copy dotfiles when deploying apps. This caused the new product page [1] to fail to deploy because `.ruby-version` is read by `Gemfile` during deploy but was not present.
Experimentally this command does copy dotfiles, copies into the root of `files-to-push`, and works regardless whether `files-to-push`.
[1] https://github.com/alphagov/paas-product-page/pull/26
I'm not certain that the CI server's `cp` and shell will behave the same way, so it might be best to try this out.
Not @46bit
> [#151010442] Copy dotfiles when pushing apps

- scripts/build-boshrelease-pipelines.sh
As part of #151322324, we've decided that we would like to fork the
upstream route-registrar repo in order to extend its functionality to
support the TLS port. This work has already been done but not merged in.
See: cloudfoundry/route-registrar#18 opened by GOV.AU.
We intend to go back into using the upstream release as soon as there is
a similar fix merged in, making this commit obsolete.
- Sanity check should be sufficient.
Neither @bandesz nor myself.
> [#151322324] Add route-registrar pipeline

- scripts/build-boshrelease-pipelines.sh
Previous commit is pointing to the wrong repository, which is an actual
route-registrar whilst we're after an actual boshrelease repo...
We're supplementing that with this change.
My bad. I'm sorry 😞 
- Sanity check
- Check if the repo actually exists and is the boshrelease repo...
> [#151322324] Change the release repository

- scripts/integration-test-pipelines.sh
Add the Elasticache broker integration tests.
This depends on https://github.com/alphagov/paas-docker-cloudfoundry-tools/pull/102, which should be merged and built first.
Make sure the integration tests run successfully.
Remove the temporary commit which pins the dev branch of the Elasticache broker.
Anyone but me or @camelpunch
> [#152670228] Add Elasticache integration tests

- scripts/build-boshrelease-pipelines.sh
This adds a new pipeline to build the elasticache-broker BOSH release
This PR is part of https://github.com/alphagov/paas-cf/pull/1123.
Sanity check. We tested the pipeline in our dev environment.
Not @samcrang or @bandesz
> [#152670292] Add BOSH release build for the elasticache-broker

- Makefile
- app-deploy.d/rubbernecker
- scripts/upload-rubbernecker-secrets.sh
Add a pipeline to deploy rubbernecker.
It may be enough to code-review this - I've tested it in a dev build concourse.
In order to test in a dev build concourse, it's necessary to:
* configure the dev build concourse with a `CF_API`, `CF_USERNAME` and `CF_PASSWORD` pointing at a dev CF deployment.
* open up the dev CF deployments API security group to the dev build concourse.
* upload the rubbernecker secrets to the dev build concourse
* run the setup pipeline
* run the rubbernecker pipeline
🚨  Before merging...
* Merge https://github.com/alphagov/paas-rubbernecker/pull/28
* Remove the `TMP` commit here.
Not me.
> [#138512111] Deploy rubbernecker

- pipelines/integration-test.yml
As it turns out, the integration tests require some secrets in order to
connect to the compose API and run checks before creating a tag release.
This parameter should allow the script to obtain the path to it and fill
in the gaps.
- Sanity check of the solution should be enough
- Optionally, in your dev build concourse, run the `compose-broker` and hope for it to be successful - I haven't done that step
> Point to a secret file

- pipelines/deploy-app.yml
- scripts/build-app-deployment-pipelines.sh
**Advice:** *Merge this before the `paas-product-page` and `paas-tech-docs` PRs or else you will have to kick off their deploy pipelines manually.*
* Use a new version of the `governmentpaas/cf-cli` Docker container that contains the autopilot `cf` plugin (see the already-merged https://github.com/alphagov/paas-docker-cloudfoundry-tools/pull/103.)
* Add ability to specify a docker image tag name for app deploys. This helped us and will aid future development work.
* Code review.
* Use our build environment to test these changes. See the Pivotal story for details.
* 🐝 Remove the `TMP` commit before merging.
Not @46bit @camelpunch
> [#153091168] Use updated cf-cli docker container with autopilot plugin

- Makefile
- README.md
- pipelines/deploy-app.yml
- pipelines/setup.yml
- scripts/build-app-deployment-pipelines.sh
- scripts/deploy-setup-pipelines.sh
Add CF_APPS_DOMAIN and pass it to the deploy jobs.
Currently the jobs like paas-product-page or paas-tech-docs use the production domain which makes testing in dev hard.
❗️ This PR contains a temporary commit to set the paas-product-page and paas-tech-docs projects to a dev branch. Please remove it before merging.
1. Update your build Concourse:
```BRANCH=redirect_cf_domain_153697787 CF_API=https://api.${DEPLOYER_DEPLOY_ENV}.dev.cloudpipeline.digital CF_APPS_DOMAIN=${DEPLOYER_DEPLOY_ENV}.dev.cloudpipelineapps.digital SELF_UPDATE_PIPELINE=false make dev pipelines```
1. Change temporarily the ${DEPLOYER_DEPLOY_ENV}-cf-api security group to allow traffic from your build Concourse
1. Test the other PRs in this story:
* https://github.com/alphagov/paas-tech-docs/pull/105
* …
> [#153697787] Set CF_APPS_DOMAIN and pass it to the deploy jobs

- pipelines/build-release.yml
- scripts/build-boshrelease-pipelines.sh
- scripts/deploy-setup-pipelines.sh
Adds the loggregator-release pipeline
We have to use a forked version of the loggregator-release to add a drain script.
Additional changes:
- make the CF_APPS_DOMAIN really optional
- Use Bosh CLI v2 for building BOSH releases (v1 was not able to handle sha256 checksums)
Test as part of https://github.com/alphagov/paas-cf/pull/1183
Not @keymon or @bandesz
> [#153561855] Add loggregator release pipeline

- scripts/integration-test-pipelines.sh
Remove FIXME now that the paas-billing changes have been deployed to CI.
1. Code review.
1. Confirm that the [existing pipeline has been renamed](https://concourse.build.ci.cloudpipeline.digital/teams/main/pipelines/paas-billing).
@bandesz reviewed the original PRs, but anyone else can review this because it's relatively simple.
> [#154524416] Remove FIXME for paas-billing rename

- Makefile
- pipelines/deploy-app.yml
- pipelines/setup.yml
- scripts/build-app-deployment-pipelines.sh
- scripts/deploy-setup-pipelines.sh
Our dev environments are now using ACM provided certs, so this flag is
no longer needed.
Code review may be enough. Verify that this only affects dev environments.
I've been using this in my dev build concourse to test deployments to my dev CF deployment.
Not me.
> [#154249348] Remove --skip-ssl-validation flag in dev.

- pipelines/build-release.yml
[#155178552 Monitor Redis queue length for ELK stack](https://www.pivotaltracker.com/story/show/155178552)
What?
-----
After upgrading the bosh cli to v2 as part of the PR
alphagov/paas-release-ci#51 we dropped the option `--name`,
as it was not docummented online [1].
But after doing that, releases like datadog-for-cloudfoundry would
get a different name than before (e.g. paas-datadog-for-cloudfoundry
instead of datadog-for-cloudfoundry.
We add again the explicit option `--name` to fix this.
[1] https://bosh.io/docs/cli-v2.html
How to review?
-------------
- Code review
- trust me, it works :)
Or:
1. Rerun any build release job, e.g.: https://concourse.build.ci.cloudpipeline.digital/teams/main/pipelines/datadog-for-cloudfoundry-release/jobs/build-dev-release/builds/75
2. Login in …
> [#155178552] Explicitly set release name when creating release

- pipelines/build-release.yml
[#155178552 Monitor Redis queue length for ELK stack](https://www.pivotaltracker.com/story/show/155178552)
> **Note:** Same than fa60d8512699a8b7cfce21f9912dbf353c4fadbb but for the
master branch
What?
-----
After upgrading the bosh cli to v2 as part of the PR
alphagov/paas-release-ci#51 we dropped the option `--name`,
as it was not docummented online [1].
But after doing that, releases like datadog-for-cloudfoundry would
get a different name than before (e.g. paas-datadog-for-cloudfoundry
instead of datadog-for-cloudfoundry.
We add again the explicit option `--name` to fix this.
[1] https://bosh.io/docs/cli-v2.html
How to review?
-------------
- Code review
- trust me (AGAIN!), it works :)
Or:
1. Rerun any build release job, e.g.: …
> [#155178552] Explicitly set release name when creating release (and 2)

- pipelines/build-release.yml
We have recently updated all our pipelines to use BOSH CLI v2 commands
and updated the bosh-cli-v2 image along the way.
To keep consistency with our other repos we are bumping the image used
here too.
This is a tricky one to test since each bosh release will rely on the container. You may want to ensure running one or more of the bosh-related build jobs still run successfully.
Not @chrisfarms or @bandesz
> [#186288969] Update to latest bosh-cli-v2 container

- .github/PULL_REQUEST_TEMPLATE.md
- pipelines/plain_pipelines/paas-team-manual.yml
https://www.pivotaltracker.com/story/show/156658598
What
----
We want to automatically upload the paas-team-manual to Github pages.
Add a pipeline that will build the paas-team-manual and push it as a github page.
Target URL: https://alphagov.github.io/paas-team-manual/
For simplicity we use the `rake publish` task directly, which requires run
git to create a branch for gh-pages and push it.
The job must:
- Install the dependencies for ruby, git and ssh
- Configure git+ssh: set user, ssh key, rewrite origin url...
We do install the dependencies in the job itself to keep the pipeline
simple and not worry to generate a new container only for this. This
task will rarely run and we do not mind some more time installing
dependencies.
We use ruby debian because it is easier to get the ruby …
> Publish paas-team-manual to Github Pages

- scripts/integration-test-pipelines.sh
What
----
paas-accounts is a mini service for storing details of PaaS
users/accounts that we cannot store within the platform itself.
This adds a pipeline for tagging merges to master as versioned releases.
How to review
-------------
Code review
Who can review
--------------
Not @chrisfarms or @dcarley
> [#156922228] Add pipeline for paas-accounts

- pipelines/build-release.yml
- pipelines/plain_pipelines/paas-product-page.yml
- pipelines/plain_pipelines/paas-tech-docs.yml
- pipelines/plain_pipelines/rubbernecker.yml
- pipelines/setup.yml
Update Ruby version to 2.5
We decided to use the same (latest) Ruby version everywhere. We still used 2.2 in multiple places which reached EOL on 2018-03-31 (#1), so we decided to migrate to the latest stable version.
We had to upgrade govuk-lint as older versions didn't support Ruby 2.5. Thanks to the upgrade we've got new style check violations but we decided to ignore them (at least for now), as this would unnecessarily blow up the story and increase the risk.
#1 https://www.ruby-lang.org/en/downloads/branches/
1. Create a new CI env from scratch from this branch
```
BRANCH=upgrade_ruby_153119909 SELF_UPDATE_PIPELINE=false make dev build-concourse bootstrap
```
1. Upload the necessary secrets (see readme)
1. Update the pipeline
```
BRANCH=upgrade_ruby_153119909 …
```
> [#153119909] Upgrade Ruby to 2.5

- scripts/integration-test-pipelines.sh
What
----
This PR adds the new rds-metric-collector into the integration
testing and tagging pipeline process we use. The boshrelease is handles
as part of the RDS broker process as the two will coexist.
How to review
-------------
Code review should suffice. Feel free to push to a dev build concourse if you wish.
Who can review
--------------
Not @keymon or @LeePorte
> [#157084165] Add rds-metric-collector to integration pipelines

- scripts/integration-test-pipelines.sh
What
----
In order to achieve automatic version bumpin, we'd need to add it to the
list of application that have integration tests build in.
How to review
-------------
- Make sure the change makes sense.
Dependencies
-------------
This PR is second in the chain of PRs.
Merge after the: alphagov/paas-admin#61
Merge before the: alphagov/paas-cf#1386
> [#156721553] Enable paas-admin to receive version bump

- scripts/build-boshrelease-pipelines.sh
We decided to remove Graphite and Grafana, as we're mostly using Datadog for metrics collection and the effort required to maintain them doesn't seem worth it.
We don't need these pipelines anymore.
Code review should be enough, I don't think it's worth to spin up a CI environment for this.
There is a quick-and-dirty test against your deployer Concourse:
```
CONCOURSE_URL=https://deployer.${DEPLOY_ENV}.dev.cloudpipeline.digital/ make dev boshrelease-pipelines
```
but then you have to manually remove all the BOSH release pipelines:
```
./bin/fly -t ${DEPLOY_ENV} destroy-pipeline -p rds-broker-release -n
./bin/fly -t ${DEPLOY_ENV} destroy-pipeline -p datadog-for-cloudfoundry-release -n
./bin/fly -t ${DEPLOY_ENV} destroy-pipeline -p logsearch-for-cloudfoundry-release -n
./bin/fly -t …
```
> [#156368115] Remove graphite and grafana pipelines

- scripts/integration-test-pipelines.sh
What
----
In order to achieve automatic version bumping, we'd need to add it to the
list of application that have integration tests build in.
How to review
-------------
- Sanity check
Dependencies
----
This is the second PR out of three.
Needs to be merged after: alphagov/paas-log-cache-adapter#2
Needs to be merged before: alphagov/paas-cf#1396
> [#158353106] Enable log-cache-adapter to receive version bump

- Makefile
- scripts/integration-test-pipelines.sh
- scripts/upload-aiven-secrets.sh
What
----
These tests interact with the Aiven API and therefore require a token and the name of the project to put the service instances into.
The secrets have already been uploaded as part of the related pull request: https://github.com/alphagov/paas-credentials/pull/120
How to review
-------------
I recommend just code review and we can raise a new pull request if it requires changes. This is because spinning up a dev CI environment takes a very long time.
Who can review
--------------
Anyone but me or @samcrang
> [#157737869] Add Aiven broker to integration tests

- scripts/upload-rubbernecker-secrets.sh
What
----
This was renamed in the store[1], but this script wasn't updated to
account for the change
[1]https://github.com/alphagov/paas-credentials/commit/0030695
How to review
-------------
Code review. Optionally test the `upload-rubbernecker-secrets` task.
Who can review
--------------
Not me.
> Update paas-pass path for rubbernecker pivotal token

- scripts/upload-aiven-secrets.sh
We now have a dedicated project in Aiven for running integration tests,
so this can be hard-coded in the upload script. We also hard-code the
pass path for the ci token as that's the one that has access to this
project.
How to review
-------------
Code review is probably enough. Compare with the corresponding credstore PRs.
* Ensure the credstore PR is merged, and you've pulled latest master.
* Upload the Aiven creds (`make ci upload-aiven-secrets`)
* Verify the Aiven broker integration tests still work.
Who can review
--------------
Not me.
> [#158943533] Tweak Aiven testing secrets upload for new projects.

- Makefile
- pipelines/plain_pipelines/paas-hackmd.yml
- scripts/upload-hackmd-secrets.sh
What
----
This PR adds a target to upload the secrets we use for Github oAuth against Hackmd running on the PaaS. In addition it uses these secrets and sets the additional env vars required for hackmd to be configured with authentication.
How to review
-------------
Code review should suffice.
Who can review
--------------
Not @LeePorte
> [#158873930] Hackmd GitHub auth

- scripts/fly_sync_and_login.sh
What
----
A Concourse `fly` binary v3.x cannot, in every situation, `fly sync` itself to a v4.x version (see [1]).
This commit:
- changes our wrapper script's logic so that it *can* sync itself back and forth across these major versions and
- puts the logic into consumable functions, for clarity.
This removes our previous file timestamp-based logic, which isn't needed.
Finally, the script now exits early if any required envvars aren't set. Whilst orthogonal, this should be uncontroversial and "obviously" the right thing to do.
[1] https://concourse-ci.org/download.html#v400
How to review
-------------
1) code review
2) manual integration tests:
(**NB this may be a bit over-enthusiastic. You might just prefer to test a 3->4 upgrade instead of the full matrix**)
You're going to run a matrix …
> [#158180318] Upgrade fly-login wrapper to cope with Concourse 4 upgrade

- scripts/build-boshrelease-pipelines.sh
This is a new Bosh release for deploying the Metric Exporter[1].
[1] https://github.com/alphagov/paas-metric-exporter
How to review
-------------
Code review only.
Who can review
--------------
Anyone but me.
> [#159174283] Add paas-metric-exporter-boshrelease

- scripts/build-boshrelease-pipelines.sh
What
----
We are having trouble running the capi-release[1]. One solution seems
to be rebuild our own release tarball, without changes.
Other option is to use precompile releases, but as commented
by @jpluscplusm
"our IA "2 eyes" continuous deployment "agreement" is based on the
potential for us to examine the code we're running in prod, and how that
interacts with upstream's CI process and security guarantees. In the
case of An Issue, could we 100% point at the code we're running?"
Because that, we decided to use our build release from code.
[1] https://cloudfoundry.slack.com/archives/C07C04W4Q/p1541779348165300
[2] https://github.com/cloudfoundry/cf-deployment/issues/663
How to review
-------------
Code review
Who can review
--------------
not me
> [#161544435] Build our own capi-release

- Makefile
- README.md
- scripts/pause-pipelines.sh
What
----
We often want to redeploy Concourse, which can be disruptive when there
are many pipelines potentially running integration tests against 3rd
party APIs. These helpers will allow quick pausing and unpausing of all
pipelines, which I have needed to do several times in the past.
How to review
-------------
Run both `make` targets. I didn't test pausing a single pipeline, but added the logic out of a lack of self-control over scope creep.
Who can review
--------------
Anyone but me.
> [#162083591] Add helper script for pausing pipelines

- pipelines/build-release.yml
- pipelines/destroy.yml
- pipelines/integration-test.yml
- pipelines/plain_pipelines/paas-hackmd.yml
- pipelines/plain_pipelines/paas-product-page.yml
- pipelines/plain_pipelines/paas-team-manual.yml
- pipelines/plain_pipelines/paas-tech-docs.yml
- pipelines/plain_pipelines/rubbernecker.yml
- pipelines/setup.yml
What
----
We are having load issues on our build CI, as all the resources
are checking for new versions across all the pipelines.
But we only want to check for those resources that trigger pipelines,
as the rest of the resources are checked as soon as each job is
triggered.
We will increase `check_every` to a big period for all non triggering
resources. We pick `24h`, to effectivelly disable the checks
on these resources.
For the resources that actually trigger the pipeline, we will keep
the default of 1m, but set it explicitelly to 1m.
More info:
[1] https://github.com/concourse/concourse/issues/1842
[2] https://github.com/concourse/concourse/issues/1445
How to review
-------------
Code review
Who can review
--------------
Not me
> [#SUPPORT] Reduce the check interval for all resources

- scripts/build-boshrelease-pipelines.sh
What
----
We want to add the job names to the Concourse (Prometheus) metrics exporter. As it's not available in any upstream yet we have to fork the Concourse Bosh release and build our own patched version
How to review
-------------
The fork is based on v4.2.1
Code review
I didn't create PRs for the forked repos, but for a code review:
* https://github.com/alphagov/paas-concourse-bosh-release/compare/v4.2.1..gds_master
* https://github.com/alphagov/paas-atc/compare/f8bd990b2a64b380651ebb6c5999bbcad10de293...783245b332d8f6e4cf5916f0b3b990eed4b9b5ba
The original upstream PR is: https://github.com/concourse/concourse/pull/2785
Who can review
--------------
Not me.
> [#162448881] Add Bosh release pipeline for our Concourse Bosh release fork

- scripts/build-boshrelease-pipelines.sh
What
----
https://github.com/alphagov/paas-drone-agent-broker-boshrelease
At the moment the release is completely untested, so it's likely that it
will need a bit of iterating once it's enabled.
How to review
-------------
* Code review of this PR should be enough
Who can review
--------------
* Not @richardTowers
> Add a build for the drone agent broker's release

- scripts/build-boshrelease-pipelines.sh
What
----
We need to fork the AWS CPI to add support for the newer EC2 instance types. This adds the build pipeline for it.
How to review
-------------
Code review
Who can review
--------------
Not me.
> [#163263881] Add BOSH release pipeline for our bosh-aws-cpi-release fork

- pipelines/plain_pipelines/paas-hackmd.yml
- pipelines/plain_pipelines/paas-product-page.yml
- pipelines/plain_pipelines/paas-tech-docs.yml
- pipelines/plain_pipelines/rubbernecker.yml
What
----
Updates the stack for rubbernecker, paas-tech-docs, paas-product-page and hackmd to cflinuxfs3
How to review
-------------
Deploy CF apps as we don't have access to the build env
Who can review
--------------
Not @mogds @AP-Hunt
> [#163363939] Update CF apps to cflinuxfs3

- pipelines/plain_pipelines/paas-hackmd.yml
What
----
This looks like it hasn't been tested since it was added - the last
hackmd build didn't use the secrets resource.
The path is wrong because there's a `cd` higher up in the script.
How to review
-------------
* Look at https://concourse.build.ci.cloudpipeline.digital/teams/main/pipelines/paas-hackmd/jobs/deploy/builds/12
* Code review
Who can review
--------------
> Fix path to hackmd-secrets in hackmd build

- pipelines/plain_pipelines/paas-hackmd.yml
What
----
The last attempt didn't work, because the manifest specifies the path
too. Best to just remove the `cd`.
How to review
-------------
* Code review
Who can review
--------------
> Remove broken `cd` in hackmd build

- pipelines/plain_pipelines/paas-hackmd.yml
What
----
`cf bgd` needs the apps to declare their bound services in their
manifests. It looks like this got lost in a refactoring at some point,
so putting it back in here.
From the git history it looks like we also need the CF_DB environment
variable setting.
How to review
-------------
* Code review
Who can review
--------------
* Not @richardtowers
> Add hackmd-db to the hackmd manifest

- pipelines/plain_pipelines/paas-hackmd.yml
What
----
The old secret has been rotated just in case having it as the ID
inadvertantly leaked it anywhere.
How to review
-------------
* Code review
Who can review
--------------
> Fix the order of github clientid / secret

- scripts/build-boshrelease-pipelines.sh
What
----
https://github.com/alphagov/paas-s3-broker-boshrelease
At the moment the release is completely untested, so it's likely that it
will need a bit of iterating once it's enabled.
How to review
-------------
* Code review of this PR should be enough
Who can review
--------------
Not @tnwhitwell
> Add a build for the S3 broker's release

- scripts/build-boshrelease-pipelines.sh
What
----
In #99, s3-broker was added, but when duplicating the previous line, `log-cache` was not replaced with `s3-broker` meaning the log-cache job was replaced with the s3-broker one.
This fixes that.
How to review
-------------
Just a review of the changes.
Who can review
--------------
Not @tnwhitwell
> Fix a flub in build-boshrelease-pipelines

- Makefile
- scripts/pause-pipelines.sh
What
----
Pausing the pipelines is done so that create-bosh-concourse can be run
without causing problems. It therefore doesn't make sense to pause this
pipeline as it's the one that's about to be run.
I've also added help text for these targets so that they appear in the `make help` output.
How to review
-------------
* Code review.
* Check the `make help` output looks sensible
* Run `make ci pause-all-pipelines` and observe that all except `create-bosh-concourse` get paused.
Who can review
--------------
Not me.
> Skip create-bosh-concourse when pausing pipelines.

- pipelines/plain_pipelines/paas-hackmd.yml
- pipelines/plain_pipelines/paas-product-page.yml
- pipelines/plain_pipelines/paas-team-manual.yml
- pipelines/plain_pipelines/paas-tech-docs.yml
- pipelines/plain_pipelines/rubbernecker.yml
- pipelines/setup.yml
- scripts/build-boshrelease-pipelines.sh
- scripts/deploy-setup-pipelines.sh
- scripts/environment.sh
- scripts/integration-test-pipelines.sh
- scripts/plain-pipelines.sh
What
----
Get Slack notifications when things deployed by our build CI fail to deploy.
Recently runs 186, 188, 189, 190, 191, 194, 196, 197, 198, 199, 201, 204 and 205 of the `paas-tech-docs` release pipeline failed, delaying some changes from going live by as much as two weeks!
See commit message for many more details.
How to review
-------------
* Code review;
* Review alongside https://github.com/alphagov/paas-credentials/pull/148
Who can review
--------------
Not @46bit
> Add Slack notifications when deploys from CI fail

- scripts/integration-test-pipelines.sh
What
----
Adds paas-service-broker-base repo to integration tests list, so that its tests can be run in Concourse rather than Travis
https://github.com/alphagov/paas-service-broker-base/pull/2 is merged. It contains the necessary Concourse task 
How to review
-------------
1. Code review
2. Deploy to a local build concourse and test?
Who can review
--------------
Anyone
> [#165715568] Adds paas-service-broker-base repo to integration tests list

- scripts/build-boshrelease-pipelines.sh
What
----
The release name needs to be cflinuxfs3 exactly. Doesn't work with the
prefix and suffix.
How to review
-------------
* Code review is enough
Who can review
--------------
> Fix release name for cflinuxfs3

- scripts/build-boshrelease-pipelines.sh
What
----
https://github.com/alphagov/paas-cf-awslogs-boshrelease renamed to https://github.com/alphagov/paas-awslogs-boshrelease because we have made it more generic and the longer name was unreadable.
How to review
-------------
Code review
Who can review
--------------
Not @46bit
> [#166351405] Rename the awslogs boshrelease for clarity

- scripts/build-boshrelease-pipelines.sh
What
----
cf-deploy currently fails when using the paas-uaa-release as it expects the release name to be uaa. This changes the name from paas-uaa to uaa.
How to review
-------------
Code review
Who can review
--------------
Not me
> Update paas-uaa-release pipeline's release name

- pipelines/plain_pipelines/rubbernecker.yml
Signed-off-by: Toby Lorne <toby.lornewelch-richards@digital.cabinet-office.gov.uk>
What
----
We do not use nodejs in rubbernecker anymore so we do not need the build
step. Also we do not need to use rubbernecker-tools which was never put
in a proper build system, we can use an upstream golang image.
How to review
-------------
Code review
Witness green pipeline: https://concourse.build.ci.cloudpipeline.digital/teams/main/pipelines/rubbernecker
Ensure this pr is merged: https://github.com/alphagov/paas-rubbernecker/pull/60
Who can review
--------------
Not @tlwr
> Use go1.12 for rubbernecker and remove build step

- pipelines/build-release.yml
What
----
Exposing the version as an environment variable will help plumb together UAA in https://github.com/alphagov/paas-uaa-release/commit/20e64e877592ddfe9d64770402c353066160bba4#diff-e084dd0a5cbd5fccbb1ff2ef0e946e05R26-R32
How to review
-------------
Code review.
Who can review
--------------
Not @46bit. @tlwr might know if there's already a BOSH env variable available to `pre_packaging` with this in?
> [#167804765] Expose VERSION as environment variable

- scripts/build-boshrelease-pipelines.sh
What
----
For our metrics and logging prototype we need to deploy jobs to BOSH
managed VMs, so we need a bosh release for those things
Add a standard bosh pipeline
How to review
-------------
Code review
Look at https://github.com/alphagov/paas-observability-release and make sure it looks right
Who can review
--------------
Not @tlwr
> Add prototype observability boshrelease repo

- pipelines/setup.yml
- scripts/build-boshrelease-pipelines.sh
- scripts/deploy-setup-pipelines.sh
- scripts/environment.sh
- scripts/fly_sync_and_login.sh
[Story](https://www.pivotaltracker.com/story/show/168427704)
🐝 This is contingent on https://github.com/alphagov/paas-bootstrap/pull/307 🐝 
What
----
Get concourse to use the secret in credhub instead of one in S3
How to review
-------------
I bootstrapped a Concourse and got it to self-update pipelines:
Who can review
--------------
Not @tlwr
> Use concourse secret in credhub for pipelines

- pipelines/plain_pipelines/build-docker-containers.yml
- pipelines/plain_pipelines/build-docker-pull-requests.yml
- scripts/environment.sh
- scripts/plain-pipelines.sh
What
----
This adds two pipelines that build docker containers to our build concourse.
This is so we can migrate from Docker Hub's Automated Builds.
`build-docker-containers.yml` is triggered when a branch is merged to
master. `build-docker-pull-requests.yml` is triggered when a pull request is
raised and tags the image with pr-build, pr-branch-name and hash. `pr-build` is
specified because the registry-image-resource defaults to latest.
In order to push the images to Docker Hub, this adds the username/password from
the password store.
How to review
-------------
- Code review
- Test using mobuild concourse or build concourse. If using mobuild, let me know so I can provide the dockerhub details.
Who can review
--------------
Not me
> [#166501543] Build Docker Containers In Concourse

- pipelines/plain_pipelines/paas-tech-docs.yml
What
----
Since [merging a gem upgrade](https://github.com/alphagov/paas-tech-docs/pull/288) the `paas-tech-docs` pipelines on the build concourse have [been failing](https://concourse.build.ci.cloudpipeline.digital/teams/main/pipelines/paas-tech-docs/jobs/test/builds/10) with errors like the following:
> bundle exec middleman build
> Could not find rack-2.1.1 in any of the sources
> Run `bundle install` to install missing gems.
It turns out that `paas-tech-docs` has a `dependencies` Make target that the pipeline wasn't invoking.
I checked locally and there are no `Gemfile.lock` changes made when invoking it, so I don't think that it's a problem with `paas-tech-docs`. I'm *guessing* that this worked until now because the Gems being used happened to be in the Docker container.
How to …
> Pipeline must install paas-tech-docs dependencies

- pipelines/plain_pipelines/paas-tech-docs.yml
What
----
Carries on from #133. This fix is hacky but `cp -pr "." files-to-push` failed and it isn't worth the time to investigate.
How to review
-------------
See that it fixed things when I deployed it.
❌ Before: https://concourse.build.ci.cloudpipeline.digital/teams/main/pipelines/paas-tech-docs/jobs/deploy/builds/11
✅ https://concourse.build.ci.cloudpipeline.digital/teams/main/pipelines/paas-tech-docs/jobs/deploy/builds/12
Who can review
--------------
Not @46bit.
> Further fix the paas-tech-docs pipeline

- pipelines/plain_pipelines/paas-hackmd.yml
- scripts/upload-secrets/upload-hackmd-secrets.sh
What
----
Some of the assets need to be pre-built before pushing them up, as
`nodejs_builtpack` does not install devDependencies on staging, therefore
is incapable of building the project.
At the moment, each re-deployment of an application will delete the
uploads provided from the users. This should be fixed, when we use S3
for storage purpose.
We're going to be generating a new secret everytime we run
`make upload-hackmd-secrets`, meaning we have an easy way to rotate the
secret, but also ensure that the secret persist in the bucket for long
enough, to be pulled out and used by the application itself, to use for
session encryption.
This should ensure, that restarting or re-scheduling the application
will not log everyone out at all times. It also means, we can have more
than a single …
> Tune CodiMD pipeline

- pipelines/integration-test.yml
- scripts/integration-test-pipelines.sh
What
----
Now that we're uploading the secrets that used to live in S3 to Credhub, we no
longer need to pass the secrets file to the integration tests task file, or
mention it at all in the pipeline.
Also changes the branch for the aiven broker tests back to `master`.
How to review
-------------
1. Code review
2. See that [this aiven broker PR has paased](https://concourse.build.ci.cloudpipeline.digital/teams/main/pipelines/aiven-broker/jobs/integration-test/builds/5) based on [this commit](https://github.com/alphagov/paas-aiven-broker/pull/23/commits/feb8e2d7e31df007d7c79d01bc8199c07249dce6)
Who can review
--------------
Anyone
> Remove references to secrets file from integration test pipeline

- pipelines/plain_pipelines/paas-product-pages.yml
What
----
- Add a task to build the static app
- Move on_failure hook to job level, so it fails for either build or push
How to review
-------------
Check [the pipeline](https://concourse.build.ci.cloudpipeline.digital/teams/main/pipelines/paas-product-pages/jobs/deploy/builds/6) is green
Who can review
--------------
@kr8n3r
> Build PaaS product pages

- pipelines/build-release.yml
- pipelines/integration-test.yml
- pipelines/plain_pipelines/build-docker-pull-requests.yml
What
----
[jtarchie/pr](https://github.com/jtarchie/github-pullrequest-resource) is deprecated
teliaoss/github-pr-resource now supports disabling forks, so we can use it instead
Read https://github.com/telia-oss/github-pr-resource#migrating
> Use github-pr-resource instead of jtarchie/pr

- pipelines/plain_pipelines/build-docker-containers.yml
- pipelines/plain_pipelines/build-docker-pull-requests.yml
What
----
When we replace docker hub builds, and get faster builds, we should keep the behaviour of:
- tagging the image with the branch name (this is already done for PR builds)
- tagging the image with the _git_ commit sha (this is currently not done for either HEAD or PR builds)
We should not keep the current behavior of tagging the image with the image digest, as we can refer to the image by digest without the indirection of a tag: `digest: sha256:123456...etc`
We should also trigger image builds when HEAD changes
How to review
-------------
Code review
> Trigger docker build when HEAD changes, and tag images according to branch

- .travis.yml
- scripts/integration-test-pipelines.sh
What
----
This commit adds an "integration test" pipeline for the new https://github.com/alphagov/paas-prometheus-endpoints repo.
We don't have any integration tests for that repo yet, but in time we may and the pipeline will make version tags in the repo which is useful to pin to in `paas-cf`.
How to review
-------------
Code review.
Who can review
--------------
Not @46bit.
> [#171281178] Versioning pipeline for paas-prometheus-endpoints

- scripts/integration-test-pipelines.sh
What
----
In line with [recent GDS guidance](https://docs.google.com/document/d/1LpBxQ9zJZp7c4eygTMWBQzGNtb9hMh-2SEV3jOlLLxY/edit?ts=5f10079a) we're going to use `main` as the branch name for new repositories.
How to review
-------------
Code review.
Who can review
--------------
Not @46bit
> [#171281178] paas-prometheus-endpoints default branch is main

- pipelines/build-release.yml
- pipelines/destroy.yml
- pipelines/integration-test.yml
- pipelines/plain_pipelines/build-docker-containers.yml
- pipelines/plain_pipelines/paas-hackmd.yml
- pipelines/plain_pipelines/paas-product-pages.yml
- pipelines/plain_pipelines/paas-team-manual.yml
- pipelines/plain_pipelines/paas-tech-docs.yml
- pipelines/plain_pipelines/rubbernecker.yml
- pipelines/setup.yml
- scripts/upload-secrets/upload-github-secrets.rb
What
----
We no longer want to fully rely on docker, due to the changes they've made to their rate limiting and image retention.
We're adding an additional registry in the shape of GitHub Container Registry. Along with that, we need authentication method sorted.
Also, some visual aids have been added into the mix to make my life easier.
How to review
-------------
- Commit by Commit code review recommended
- Push secrets `make ci credhub && make ci upload-github-secrets`
- Set pipelines `make ci plain-pipelines`
- See jobs running in CI concourse
> Setup additional registry

- pipelines/plain_pipelines/paas-tech-docs.yml
- pipelines/plain_pipelines/rubbernecker.yml
What
----
Switch `cf push zdt` for `cf push --strategy rolling`
We are now using cf cli v7 where `--strategy rolling` is built in. we no
longer install the zero-downtime plugin in the container, [which causes failures](https://concourse.build.ci.cloudpipeline.digital/teams/main/pipelines/paas-tech-docs/jobs/deploy/builds/63)
How to review
-------------
Code review
Who can review
--------------
Anyone
> Switch `cf push zdt` for `cf push --strategy rolling`

- pipelines/plain_pipelines/build-docker-containers.yml
What
----
Add a job for building and deploying paas-prometheus-exporter, so that users can deploy as a docker app instead of a buildpack app if they want.  This is easier, for example, when deploying using terraform.
Merge after https://github.com/alphagov/paas-prometheus-exporter/pull/38
> Build paas-prometheus-exporter

- pipelines/plain_pipelines/build-docker-containers.yml
- pipelines/plain_pipelines/build-docker-pull-requests.yml
DockerHub recently started rate limiting image pulls. We aren't giving credentials to all production pipelines, and so our effective rate limit is quite low.
We are stopping relying on DockerHub for production CI/CD pipelines. Instead we're going to rely on GitHub Container Registry (GHCR.)
Most of our images are already being mirrored onto GHCR when they are built [1]. But we have also used some third-party DockerHub images that don't have copies on GHCR.
This commit adds tiny Dockerfiles that merely re-export those third-party images. The advantage of doing this, vs a `docker pull` and `docker push`, is that we can fit into the existing patterns of image building and CI setup.
[1] https://github.com/alphagov/paas-release-ci/blob/master/pipelines/plain_pipelines/build-docker-containers.ym …
> [#176226306] Build docker images that mirror DockerHub

- pipelines/plain_pipelines/paas-rds-broker.yml
- scripts/build-boshrelease-pipelines.sh
- scripts/plain-pipelines.sh
What
----
The RDS broker requires a slightly different set of CI actions to other repos in response to PRs and merges to the main branch. This commit removes it from the integration test pipeline setup, and creates it as a "plain" pipeline.Describe what you have changed and why.
How to review
-------------
1. Code review
1. [Check on the release CI Concourse and see if the job ran successfully](https://concourse.build.ci.cloudpipeline.digital/teams/main/pipelines/paas-rds-broker)
After merging
--------------
Deploy the new pipelines, and delete the old `rds-broker` and `rds-broker-release` pipelines
> Create a pipeline for testing and releasing paas-rds-broker

- pipelines/plain_pipelines/paas-rds-broker.yml
What
----
1. Clone submodules correctly using the git resource type
2. Perform production release compilations and integration tests in parallel, to reduce iteration times
3. Reset version numbering to begin at `1.0.0`, so that the source code and its releases share the same version numbering
How to review
-------------
1. [See that it works](https://concourse.build.ci.cloudpipeline.digital/teams/main/pipelines/paas-rds-broker) (ignore the integration test failures, they aren't related to this change)
2. Code review thoroughly. I'm not confident in my Concourse pipelines
> Improve release process for RDS broker pipeline

- scripts/plain-pipelines.sh
What
----
glob *.yml files, not just *
This allows 'x.yml.bak / x.yml.disabled' which will not be deployed
How to review
-------------
* Code review
* `touch pipelines/plain_pipelines/*.yml.not_a_yml`
* `ls pipelines/plain_pipelines/*.yml`
Who can review
--------------
Not @me
> Rather than just doing `*` select `*.yml`

- pipelines/plain_pipelines/paas-rds-broker.yml
What
----
Use the right parameter value for cloning Git resource submodules
Rather confusingly, the parameter value to enable cloning submodules is
different when using a PR resource versus a git repo resource.
For a PR: `submodules: true`
For a repo: `submodules: all`
How to review
-------------
1. [I pushed it to the CI env and it's working](https://concourse.build.ci.cloudpipeline.digital/teams/main/pipelines/paas-rds-broker/jobs/build-prod-release/builds/65)
Who can review
--------------
Me
> Use the right parameter value for cloning Git resource submodules

- pipelines/plain_pipelines/build-docker-containers.yml
What
----
Add a job to build a slack-notification-resource container image made available via the GitHub container registry.
Since DockerHub rate limits access, we require all container images used by our main deployment pipelines to be available by other means, read ghcr.io.
How to review
-------------
- Code review
- CI passes
Who can review
--------------
not @schmie
> Build slack-notification-resource

- pipelines/build-release.yml
- pipelines/integration-test.yml
- pipelines/plain_pipelines/build-docker-pull-requests.yml
- pipelines/plain_pipelines/paas-rds-broker.yml
What
----
This was the last docker registry container we had in use in CI. it has
now been pushed to ghcr.io/alphagov/paas/teliaoss-github-pr-resource so
it made sense to update the pipeline.
How to review
-------------
code review and check you can pull the image
Who can review
--------------
Anyone
> Switch teliaoss-github-pr-resource to ghcr

- pipelines/plain_pipelines/paas-tech-docs.yml
What
----
Remove `path` and `buildpack` attributes
In https://github.com/alphagov/paas-tech-docs/pull/383 we're adding a `Staticfile` to define error page templates.
There appears to be a bug where if the manifest file contains the path and buildpack attributes and the repo contains a Staticfile, any setting in the Staticfile doesn't get applied.
How to review
-------------
- you can test this by deploying https://github.com/alphagov/paas-tech-docs/pull/383 with the original and modified manifest file and check which one serve the correct error page as defined in the Staticfile.
Who can review
--------------
not @kr8n3r
> Update tech-docs deploy manifest

- pipelines/plain_pipelines/rubbernecker.yml
What
----
Currently the build fails as 1.14 no longer exists the go-buildpack as of 1.9.30 - https://github.com/cloudfoundry/go-buildpack/releases/tag/v1.9.30
```
-----> Go Buildpack version 1.9.31
WARNING buildpack version changed from 1.9.29 to 1.9.31
WARNING [DEPRECATION WARNING]:
WARNING Please use AppDynamics extension buildpack for Golang Application instrumentation
WARNING for more details: https://docs.pivotal.io/partners/appdynamics/multibuildpack.html
-----> Installing godep 80
Copy [/tmp/cache/final/dependencies/ea2dee71d88cce172a78209425e7d9fa69203481c57c75b313e2408c83b759a7/godep-v80-linux-x64-cflinuxfs3-b60ac947.tgz]
-----> Installing glide 0.13.3
Copy [/tmp/cache/final/dependencies/e0175241cc9dda53f333835198167170cda881c2154d211230494738e0e678ae/glide-v0.13.3-linux-x64-cflin …
```
> Specify newer version of GO for Rubbernecker

- pipelines/plain_pipelines/build-docker-containers.yml
- pipelines/plain_pipelines/build-docker-pull-requests.yml
What
----
Vito has migrated over to concourse-oci-build-task for the oci build
container (https://github.com/concourse/oci-build-task/commit/59854185031e972dff3291328f8ec9808b8e4782). This keeps us in line with these changes and uses our GitHub
mirror of the container in order to prevent pull related issues.
How to review
-------------
Code review
Who can review
--------------
Anyone
> Update to concourse-oci-build-task container

- pipelines/plain_pipelines/paas-rds-broker.yml
What
----
AWS applies an account-wide throttle to RDS api calls, which will lead to failures if the RDS broker's integration tests run twice simultaneously.
Use concourse's `serial_groups` feature to prevent this from happening. Hopefully choosing a name for the group which explains its purpose well enough.
How to review
-------------
Look at it and be happy.
Who can review
--------------
Anyone other than @risicle
> paas-rds-broker pipeline: give integration tests add rds-calls-throttled serial_group

- pipelines/plain_pipelines/rubbernecker.yml
What
----
In https://github.com/alphagov/paas-rubbernecker/pull/80 we updated rubbernecker to require golang 1.18. It won't deploy with `GOLANG` set to 1.16
How to review
-------------
:eyes:
> rubbernecker: use golang 1.18 for deployment

- .github/workflows/test_on_pr.yml
Description:
- go get isn't used to install but only to update so pin to main branch to always install the latest pipecleaner
What
----
Describe what you have changed and why.
How to review
-------------
Describe the steps required to test the changes.
Who can review
--------------
Describe who can review the changes. Or more importantly, list the people
that can't review, because they worked on it.
> 181929453 - Clean up Go 1.18 bits

- pipelines/plain_pipelines/paas-product-pages.yml
What
----
LTS docker image was updated to Node 18.14.0. - https://hub.docker.com/layers/library/node/lts/images/sha256-f27e3f4c8b5719cb9816084475d687a283c59149f3d11a7aa45b675fea56bed0?context=explore
Node 18.14.0 contains npm cli version 9.3.1 - https://github.com/nodejs/node/commit/66ab03d03240ab11cd415b487314c7cbcc74d7f1
Npm cli versions 9 and never no longer contain the `npm bin` command - https://github.blog/changelog/2022-10-24-npm-v9-0-0-released/#%E2%9A%A0%EF%B8%8F-notable-breaking-changes
Their recommendation is to replace it with `npx`
How to review
--------------
- someway to get Ci to use this branch ? 
Who can review
--------------
not @kr8n3r
> Replace `npm bin` with `npx` in product-pages pipeline

- pipelines/plain_pipelines/paas-tech-docs.yml
What
----
Switch the buildpack we use for the tech docs redirect deployment.
Set the buildpack to staticfile_buildpack for the tech docs main site.
How to review
-------------
Look at the change.
Who can review
--------------
Any team member.
> Buildpack changes to tech docs

- pipelines/build-release.yml
What
----
Previously we were using a forked version of this resource because we needed a `submodules` param that wasn't yet released. This param is now released and it's less maintenance to not use our fork.
How to review
-------------
Deploy this branch to the build pipeline and check that PR resources are still working.
Who can review
--------------
Anyone.
> Switch back to the OG github-pr-resource at v0.23.0

- .github/workflows/test_on_pr.yml
Description:
-------------
- Currently we pin to versions which means that we automatically pull in the latest changes which presents a security risk as we don't know which code is running in our build pipeline.
- This PR fixes this by pinning to a specific hash
- A future PR will configure dependabot to raise PR's automatically for later versions of GitHub Actions against their hashes
How to review
-------------
Verify that GitHub actions run successfully
> 185509385 - Pin GitHub Actions to specific hashes

- .github/workflows/test_on_pr.yml
- pipelines/build-release.yml
- pipelines/destroy.yml
- pipelines/plain_pipelines/paas-hackmd.yml
- pipelines/plain_pipelines/paas-nginx-hosts-reload.yml
- pipelines/plain_pipelines/paas-product-pages.yml
- pipelines/plain_pipelines/paas-rds-broker.yml
- pipelines/plain_pipelines/paas-tech-docs.yml
- pipelines/plain_pipelines/rubbernecker.yml
- pipelines/setup.yml
- scripts/fly_sync_and_login.sh
What
----
Noticed due to https://www.pivotaltracker.com/story/show/185500753 that we haven't updated the docker images used by the pipelines here in ... a long time.
To handle some of the changes, a few task alterations were needed, including using `registry-image` instead of `docker-image` as we have done almost everywhere else (in other repos).
~Depends on https://github.com/alphagov/paas-docker-cloudfoundry-tools/pull/283~
How to review
-------------
Tricky. Can possibly look at the release history of ci where this has been successfully deployed?
> pipelines: update docker images

- scripts/build-boshrelease-pipelines.sh
Description:
- UAA has been unforked and we no longer use the [paas-uaa](https://github.com/alphagov/paas-uaa) and [paas-uaa-release](https://github.com/alphagov/paas-uaa-release) repositories hence this pipeline is now unnecessary
- See [here](https://github.com/alphagov/paas-cf/pull/2909) for the commit to unfork UAA
How to review
-------------
See `setup` in https://concourse.build.ci.cloudpipeline.digital/teams/main/pipelines/setup and code review.
> 180444788-Remove-UAA-release-pipeline

- pipelines/plain_pipelines/rubbernecker.yml
Description:
----
- The default behaviour is to turn Go modules on and we don't use `go get` to install binaries anymore
- Upgrade buildpack to Go 1.20
How to review:
----
- See successful deployment at https://concourse.build.ci.cloudpipeline.digital/teams/main/pipelines/rubbernecker/jobs/deploy/builds/23
> BAU - Upgrade Rubbernecker buildpack to Go 1.20

- pipelines/build-release.yml
What
----
Some builds will provide an executable shell script called `scripts/vendor_package.sh`. If that is the case the build pipeline will execute it to call `bosh vendor-package` against a bosh release. 
This should not interfere with other boshreleases.
How to review
-------------
- check the code
- use this commit against the build ci to verify that build releases are still working
Who can review
--------------
Engineers in the paas team
> [185517739] Build pipeline supports vendored releases

- README.md
- pipelines/plain_pipelines/rubbernecker.yml
- scripts/upload-secrets/upload-cf-cli-secrets.rb
Description:
----
- Deploy Rubbernecker to London using the CI user for London
- Remove the deployment of Rubbernecker to Ireland
- Deploy the redirect app to Ireland
- Remove CF_APPS_DOMAIN and CF_SYSTEM_DOMAIN as they are unused in this step
- Add CF_LONDON_USER and CF_LONDON_PASSWORD to secrets as this account is what CI uses to deploy to the London region
How to review
-------------
- Code review
- Visit [rubbernecker.cloudapps.digital](rubbernecker.cloudapps.digital) and verify the redirect
- See https://concourse.build.ci.cloudpipeline.digital/teams/main/pipelines/rubbernecker/jobs/test/builds/40 for a successful run
> 185827364 - Add deploy to London for Rubbernecker and redirect app

- pipelines/plain_pipelines/rubbernecker.yml
Description:
----
- Bumps Go version to 1.20 in test step
- Removes unused S3-iam resource type
See successful run at https://concourse.build.ci.cloudpipeline.digital/teams/main/pipelines/rubbernecker/jobs/test/builds/46
> 185827364 - Bump rubbernecker test to Go 1.20

- scripts/integration-test-pipelines.sh
Reverts alphagov/paas-release-ci#260
There is no cf in the build environment and consequently, integration tests for the cdn broker cannot be performed there.
> Revert "[#185765129] Adding paas-cdn-broker for integration tests"

- .github/workflows/test_on_pr.yml
- go.mod
- go.sum
What
----
The github actions for paas-release-ci use go 1.20.
This is failing to compile some modules, and we need to upgrade it to at least 1.22.
Describe what you have changed and why.
----
Bump Go version to 1.22
How to review
----
Code changes
Describe the steps required to test the changes.
----
Test on dev01 pipeline
Who can review
----
GovPaaS
> Bump Go version to 1.22
