alphagov/paas-release-ci

scripts/build-boshrelease-pipelines.sh
Story: [Junk logstash mappings being created & breaking Kibana](https://www.pivotaltracker.com/story/show/131722035)
Build from our fork https://github.com/alphagov/paas-logsearch-for-cloudfoundry
Code review, the change is safe
Not @combor or me
=> [#131722035] Add logsearch-for-cloudfoundry release

scripts/build-boshrelease-pipelines.sh
Story: [Migrate existing bosh release builds to use pullrequest-resource based builds](https://www.pivotaltracker.com/story/show/132745311)
Add graphite and collectd releases. Required for PR on paas-cf that will make use of these.
code review (zero risk)
Not me
=> [#132745311] Add graphite and collectd releases

scripts/build-boshrelease-pipelines.sh
Story: [Migrate existing bosh release builds to use pullrequest-resource based builds](https://www.pivotaltracker.com/story/show/132745311)
Note: riemann was pulled as there will be more work involved
Code review
Not me
=> [#132745311] Migrate last releases

.travis.yml, README.md, scripts/deploy-pipeline.sh
[Document build concourse](https://www.pivotaltracker.com/n/projects/1275640/stories/136175989)
Document how to access the server, add some links and details. Document automated builds.
Proofread, check links work, check that text is correct.
not @mtekel
=> [#136175989] Document build concourse

scripts/environment.sh
Story: [Deployment Pipeline for Tech Docs to cloudapps.digital](https://www.pivotaltracker.com/story/show/136353551)
It was wrongly using a default value instead of reading the credentials uploaded to S3.
Test running pp deployment pipeline in dev by using a different user than "admin"
Not me
=> [#136353551] Read CF_USER from S3

scripts/build-boshrelease-pipelines.sh
As we forked 18F CDN broker and are implementing it for gov.uk paas,  we need a dev release to test. 
Sanity check
Not @combor or @paroxp
=> [#141231851] Add cdn broker to the list of release

scripts/build-boshrelease-pipelines.sh
In order to keep up with the standard we've been living up to, we're
replacing this underscore with a hyphen.
See if the character change is reasonable.
Neither @combor  nor @paroxp
=> Replace the underscore with hyphen

scripts/build-boshrelease-pipelines.sh
This is a partial revert of 734accc now that it has been deployed to the
build Concourse in the CI environment.
Code review only. I've tested it in dev.
Anyone
=> [#140847887] Remove FIXME for pipeline renaming

pipelines/build-release.yml, pipelines/deploy-app.yml, pipelines/destroy.yml, pipelines/integration-test.yml, pipelines/setup.yml, scripts/pipecleaner.py
We've upgraded concourse to the version 3.4.1 not so long ago. Although
the old templating is still supported it will be deprecated in the
future.
The new format supports proper types and variable interpolation.
Pipecleaner had to be modified in order to fit the new syntax.
- Sanity code check
- See if there aren't variables left out
- See if related `FIXME`s have been resolved
🐝 🐝 🐝 
I did not test this. I assumed the behaviour to be the same as the `paas-cf` and `paas-bootstrap` changes.
🐝 🐝 🐝
=> [#150881142] Update pipeline variables to new format

scripts/integration-test-pipelines.sh
This PR adds an integration-test pipeline for the paas-usage-events-collector project. We need this for automatically tagging releases for the project. 
I updated my dev CI and already tested the pipeline. I think a sanity check should be enough.
not me
=> [151838550] Add paas-usage-events-collector pipeline

.travis.yml, pipelines/deploy-app.yml, scripts/pipecleaner.py
This pulls in the latest changes to pipecleaner from paas-cf -
specifically, the dummy variables that it inserts before shellchecking
have had a date interpolation added so that shellcheck doesn't think
they're safe strings.
This retains the changes that have been added in da7900e to improve the
handling of external tasks.
Code review is probably enough.
Not me.
=> [#152067205] Pull in pipecleaner changes from paas-cf

.travis.yml, Makefile, pipelines/destroy.yml, pipelines/setup.yml, scripts/lint_terraform.sh
Upgrade Terraform to latest stable version.
There are two variations that you could test at your own discretion.
You might want to test it with alphagov/paas-bootstrap#117 to save time.
1. Create a Build Concourse from `master`.
1. Run the `setup` pipeline.
1. Checkout this branch and re-upload the pipelines to your Build Concourse.
1. Run the `setup` pipeline again and confirm that the Terraform job completes and doesn't modify any resources.
1. Create a Build Concourse from this branch.
1. Run the `setup` pipeline and confirm that the Terraform job completes.
:bee: :bee: :bee: Bee-fore merging :bee: :bee: :bee:
1. Merge alphagov/paas-docker-cloudfoundry-tools#107
1. Wait for Docker Hub to build and tag the container.
1. Amend the `wip` commit to use the Docker image tag that matches the …
=> [#153119879] Upgrade Terraform

app-deploy.d/rubbernecker, scripts/upload-rubbernecker-secrets.sh
We've adjusted the setup for the rubbernecker deployment. It now has some tests, therefore appropriate docker container is needed.
- Deploy from this branch to your dev build pipeline
- Run `rubbernecker` pipeline and see it succeed
- 🐝 ~~Remove the TMP commit before merging~~ 🐝
=> Adapt rubbernecker deployment

pipelines/plain_pipelines/paas-team-manual.yml
What
----
This was missed in my review of:
https://github.com/alphagov/paas-release-ci/pull/61
How to review
-------------
Code review
Who can review
--------------
@keymon
=> Fix state bucket variable name

scripts/plain-pipelines.sh
What
----
This was missed in my review of:
https://github.com/alphagov/paas-release-ci/pull/61
How to review
-------------
Code review
Who can review
--------------
I am just merging this because testing and review will waste the team's time. It is a super low risk change.
=> Fix plain pipeline variable interpolation

pipelines/plain_pipelines/paas-team-manual.yml
What
----
This was left pointing at the development branch, but we're now merging
changes to master.
How to review
-------------
Code review
Who can review
--------------
Not me
=> [#156658598] Deploy team manual from the master branch.

pipelines/plain_pipelines/paas-hackmd.yml
What
----
This pins a dev branch for now. Update this commit and message before
merging.
How to review
-------------
Review https://github.com/alphagov/paas-codimd/pull/1 first.
This pins a dev branch for now. Update this commit and message before
merging. It should pin `gds_master`, not `initial`.
Who can review
--------------
Anyone but me
=> [#158825291] Add pipeline for deploying CodiMD (HackMD)

.travis.yml, scripts/build-boshrelease-pipelines.sh
What
----
We want to build our own forked version of the cf-networking-release[1]
to include a patch for a bug in the policies-server[2]
[1] https://github.com/cloudfoundry/cf-networking-release/
[2] https://github.com/cloudfoundry/cf-networking-release/pull/60
How to review
-------------
Code review
Who can review
--------------
Anyone
=> [#162275131] Add forked cf-networking-release

scripts/build-boshrelease-pipelines.sh
We're no longer using these, so we no longer need to build them.
How to review
-------------
* Code review is probably enough.
Who can review
--------------
Not me.
=> [#162381976] Remove Datadog boshrelease pipelines

scripts/build-boshrelease-pipelines.sh
We are forking this to backport some upstream fixes.
How to review
-------------
Code review
Who can review
--------------
Not me.
=> [#163591232] Add our log-cache-release fork.

scripts/integration-test-pipelines.sh
What
----
Add the paas-s3-broker project so we can run the integration tests and we can tag releases.
How to review
-------------
Code review
Who can review
--------------
Not me.
=> [#163364037] Add the paas-s3-broker project

scripts/build-boshrelease-pipelines.sh
What
----
Adds a boshrelease for https://github.com/alphagov/paas-uaa-customized-boshrelease
How to review
-------------
Code review
Who can review
--------------
Not @tlwr
=> Add uaa-customized-boshrelease

scripts/build-boshrelease-pipelines.sh
What
----
Track https://github.com/alphagov/paas-uaa-release `gds_master`
So we can build our own UAA release
How to review
-------------
Code review
=> 165561584 Add paas-uaa-release

scripts/build-boshrelease-pipelines.sh
What
----
Fix an egregious typo of mine
How to review
-------------
Code review
=> fix paas-uaa release name

scripts/build-boshrelease-pipelines.sh
What
----
This is required to work around
https://github.com/cloudfoundry/cflinuxfs3-release/issues/5,
which is needed to release patches for a couple of Ubuntu Security
Notifications.
How to review
-------------
* Code review is enough
Who can review
--------------
=> Build paas-cflinuxfs3-release

Makefile, README.md, pipelines/setup.yml, scripts/build-boshrelease-pipelines.sh, scripts/deploy-setup-pipelines.sh, scripts/environment.sh, scripts/fly_sync_and_login.sh
What
----
This is its new name in Concourse 5 - it's already been updated in the
S3 buckets that the main pipeline lays down.
How to review
-------------
* Code review
Who can review
--------------
Maybe Lee?
=> Rename CONCOURSE_ATC to CONCOURSE_WEB

pipelines/setup.yml
See https://github.com/alphagov/paas-bootstrap/pull/279
=> Add colocated-with-web tag for self-updating tasks

pipelines/build-release.yml, pipelines/destroy.yml, pipelines/integration-test.yml, pipelines/setup.yml
What
----
This commit responds to a security bug in the alpine base image. It updated the hash of the alpine based docker containers we build and use in the pipeline.
How to review
-------------
Code review.
Who can review
--------------
anyone
=> Update docker container hash in use

scripts/build-boshrelease-pipelines.sh
What
----
Add paas-cf-awslogs-boshrelease to build-ci, so we can start iterating on it
How to review
-------------
Cod review.
Who can review
--------------
Not me!
=> [#166351405] Add paas-cf-awslogs-boshrelease to build-ci

scripts/build-boshrelease-pipelines.sh
What
----
There are a couple of boshreleases that will be needed for firebreak / random experimentation. This adds them.
How to review
-------------
Code review
Who can review
--------------
Anyone
=> Adds in some new boshreleases that are to use in firebreak

scripts/build-boshrelease-pipelines.sh
What
----
[Story](https://www.pivotaltracker.com/story/show/167370830) to archive/remove HAProxy
Whilst I'm here I've cherry-picked Miki's commit from #116, reformatted things so they are clearer, and additionally removed log-cache and traefik
How to review
-------------
Code review
Who can review
--------------
Not @tlwr
=> Remove HAProxy release (and friends)

scripts/integration-test-pipelines.sh
What
----
I'd like the app to be auto-magically bumped.
How to review
-------------
- See if repo exists
- See if repo has required files
=> Setup paas-audit-to-splunk releases

scripts/integration-test-pipelines.sh
What
----
Add a pipeline for the paas-trusted-people repo (which will be a source
of truth for who's allowed access to what).
How to review
-------------
* Code review should be enough
Who can review
--------------
@AP-Hunt
=> Add paas-trusted-people

scripts/integration-test-pipelines.sh
What
----
We've merged the two codebases into one, and we'd like to be deploying
that specific application continuously.
Replacing the old application with the new one to achieve the same
behaviour.
How to review
-------------
- Sanity check
=> Continuously release PaaS Auditor

.travis.yml, Makefile, pipelines/destroy.yml, pipelines/setup.yml, scripts/plain-pipelines.sh
What
----
See alphagov/paas-cf#2210
We have pipecleaner.py duplicated everywhere, please no
=> Use paas-cf pipecleaner

pipelines/plain_pipelines/build-docker-containers.yml, pipelines/plain_pipelines/build-docker-pull-requests.yml
What
----
Changes repo name used in docker build pipelines from username to `governmentpaas`.
How to review
-------------
Code review
Who can review
--------------
Not me
=> [#166501543] Update Docker Hub Repo Name

pipelines/setup.yml
What
----
Adds docker hub creds to the self-update pipeline
How to review
-------------
Code review
Who can review
--------------
Not me
=> [#166501543] Add docker hub creds to self-update pipeline

scripts/deploy-setup-pipelines.sh
What
----
Add docker hub creds to deploy setup pipeline
How to review
-------------
Code review
Who can review
--------------
Not me
=> [#166501543] Add docker hub creds to deploy setup pipeline

scripts/upload-secrets/upload-cf-cli-secrets.rb, scripts/upload-secrets/upload-hackmd-secrets.rb
What
----
1. Hackmd secrets used wrong variable names
2. CF cli secrets didn't trim the password
How to review
-------------
1. Code review
I've already run the scripts in the CI env to upload the secrets.
Who can review
--------------
Anyone
=> Correct secrets upload scripts

pipelines/plain_pipelines/paas-product-pages.yml
What
----
Deploys alphagov/paas-product-pages
How to review
-------------
Code review
Who can review
--------------
@kr8n3r
=> Add pipeline for paas-product-pages

.travis.yml, pipelines/build-release.yml, pipelines/destroy.yml, pipelines/setup.yml
[Story](https://www.pivotaltracker.com/story/show/173382894)
What
----
Update ruby to 2.7
Update Travis OS to Ubuntu Focal
Update docker images to include Ruby 2.7 with Alpine 3.11 and 3.12
How to review
-------------
Code review
CI
Who can review
--------------
Not @tlwr
=> [#173382894] Update travis and docker dependencies

pipelines/plain_pipelines/paas-team-manual.yml
[Story](https://www.pivotaltracker.com/story/show/173382894)
=> [#173382894] Bump ruby version for team manual to 2.7

pipelines/plain_pipelines/paas-product-pages.yml
What
----
In https://github.com/alphagov/paas-product-pages/pull/58 we've [updated the build step](https://github.com/alphagov/paas-product-pages/pull/58/files#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R10). We need to update here to have CSS & JS built
Who can review
--------------
not @kr8n3r
perhaps @tlwr
=> Update product pages build script

pipelines/plain_pipelines/paas-product-pages.yml
What
----
https://github.com/alphagov/paas-product-pages/pull/64
@kr8n3r
=> paas-product-pages: push redirect app

scripts/build-boshrelease-pipelines.sh, scripts/integration-test-pipelines.sh
What
----
we are adding an sqs-broker and want the broker integration tests +
boshrelease builds to be performed by the release ci
How to review
-------------
Is that correct?
Who can review
--------------
Not @chrisfarms
=> sqs-broker: add test/release pipelines

scripts/build-boshrelease-pipelines.sh, scripts/integration-test-pipelines.sh
What
----
These are new repositories, so we should use `main` from the start.
How to review
-------------
Look at the code
Who can review
--------------
Not @philandstuff
=> Build sqs-broker from `main` branch

.travis.yml, terraform/aws.tf, terraform/buckets-boshreleases.tf, terraform/providers.tf
What
----
Fix terraform to run with 0.13
There were a couple of issues with interpolation of variables and the
plugin syntax needed updating.
How to review
-------------
Code review
Who can review
--------------
Anyone
=> Fix terraform to run with 0.13

terraform/versions.tf
What
----
adds a versions.ft file 
How to review
-------------
code review
Who can review
--------------
@AP-Hunt
=> Added versions.tf

pipelines/plain_pipelines/build-docker-containers.yml
What
----
s/master/main/
How to review
-------------
👀
=> Build the correct branch of paas-prometheus-exporter

README.md, pipelines/plain_pipelines/build-docker-containers.yml, pipelines/plain_pipelines/paas-hackmd.yml, pipelines/plain_pipelines/paas-product-pages.yml, pipelines/plain_pipelines/paas-team-manual.yml, pipelines/plain_pipelines/paas-tech-docs.yml, pipelines/plain_pipelines/rubbernecker.yml, scripts/build-boshrelease-pipelines.sh, scripts/deploy-setup-pipelines.sh, scripts/integration-test-pipelines.sh
What
----
Update branches to `main` from `master` because it's the right thing to do.
How to review
-------------
Code review
Who can review
--------------
Describe who can review the changes. Or more importantly, list the people
that can't review, because they worked on it.
=> Update branches to `main` from master.

pipelines/plain_pipelines/build-docker-containers.yml, pipelines/plain_pipelines/build-docker-pull-requests.yml
What
----
replicated vito/oci-build-task to ghcr.io/alphagov/paas/vito-oci-build-task and fixed registry references
How to review
-------------
Code review
Who can review
--------------
@paroxp
=> GitHub build container

pipelines/plain_pipelines/build-docker-pull-requests.yml
What
----
I fixed a typo  in a URI
How to review
-------------
Code review
Who can review
--------------
Anyone
=> Fix a URI typo

pipelines/plain_pipelines/build-docker-pull-requests.yml
What
----
There was a missing container hash
How to review
-------------
Code review
Who can review
--------------
Anyone
=> Add missing container hash

pipelines/plain_pipelines/build-docker-containers.yml
What
----
For some reason there were some missing image tagging tasks, these have
been reintroduced.
How to review
-------------
Code review
Who can review
--------------
Anyone
=> Added in some missing image teg tasks

pipelines/plain_pipelines/build-docker-containers.yml
What
----
I forgot to update these
How to review
-------------
Code review
Who can review
--------------
Anyone
=> Update the resources used in the tagging stage

pipelines/plain_pipelines/build-docker-containers.yml
What
----
We actually need to use the tags we have created on the docker images
How to review
-------------
Code review
Who can review
--------------
Anyone
=> Use the tags when pushing images

pipelines/plain_pipelines/build-docker-containers.yml
What
----
Reinstates the docker latest tag
How to review
-------------
Code review
Who can review
--------------
Anyone
=> Reinstate docker latest tag

pipelines/plain_pipelines/build-docker-pull-requests.yml
What
----
Builds `paas-prometheus-exporter` PRs in to Docker containers
How to review
-------------
1. [Did it work](https://concourse.build.ci.cloudpipeline.digital/teams/main/pipelines/build-docker-pull-requests/jobs/build-paas-prometheus-exporter-pr/builds/1#L60d466f8:3)
=> [#178755576] Build paas-prometheus-exporter container from PR

scripts/build-boshrelease-pipelines.sh
What
----
Added a bosh release pipeline to build our (previously semi-)forked app-autoscaler-release @ https://github.com/alphagov/paas-app-autoscaler-release
How to review
-------------
Do we have time for this?
Who can review
--------------
Not @risicle
=> boshrelease pipelines: add our app-autoscaler fork

pipelines/plain_pipelines/paas-team-manual.yml
What
----
force team manual docker image to use new bundler
How to review
-------------
Describe the steps required to test the changes.
Who can review
--------------
Describe who can review the changes. Or more importantly, list the people
that can't review, because they worked on it.
=> force team manual docker image to use new bundler

pipelines/plain_pipelines/paas-hackmd.yml, pipelines/plain_pipelines/paas-nginx-hosts-reload.yml, pipelines/plain_pipelines/paas-product-pages.yml, pipelines/plain_pipelines/paas-rds-broker.yml, pipelines/plain_pipelines/paas-tech-docs.yml, pipelines/plain_pipelines/rubbernecker.yml
What
----
The cf cli has been upgraded to v8.7.1 as requested in Pivotal Tracker storey 185500801. Updated tag for the cf-cli image.
How to review
-------------
Code review.
Who can review
--------------
Any paas dev.
=> [#185500801] Updated tag for cf-cli image

.github/dependabot.yml
Description:
----
- Configures dependabot to update Go and Ruby dependencies
=> BAU - Configure dependabot to update Go and Ruby dependencies

scripts/integration-test-pipelines.sh
What
----
Added the paas-cdn-broker for integration tests.
How to review
-------------
Review the code.
Who can review
--------------
Any paas developer.
=> [#185765129] Adding paas-cdn-broker for integration tests

pipelines/build-release.yml, pipelines/destroy.yml, pipelines/plain_pipelines/paas-nginx-hosts-reload.yml, pipelines/plain_pipelines/paas-rds-broker.yml, pipelines/plain_pipelines/rubbernecker.yml, pipelines/setup.yml
Description:
----
- Bumps docker images to the latest version
How to review
-------------
- See run in https://concourse.build.ci.cloudpipeline.digital/teams/main/pipelines/setup/jobs/self-update/builds/109
- See run in https://concourse.build.ci.cloudpipeline.digital/teams/main/pipelines/paas-nginx-hosts-reload/jobs/build-dev-release/builds/11
- See run in https://concourse.build.ci.cloudpipeline.digital/teams/main/pipelines/rubbernecker/jobs/test/builds/51
=> 186049138 - Bump docker images

pipelines/plain_pipelines/check-github-repos.yml
What
----
Updated check-github-repos because not all paas repos will have a topic of `paas`.
How to review
-------------
1 - Review the code.
2 - Check that the build works.
Who can review
--------------
Any pass developer.
=> Updated check-github-repos
